#################################################################
# Makefile generated by Xilinx Platform Studio 
# Project:/home/eugene/homogeneous_port/src/platforms/xilinx/ml605_dual_mb/design/system.xmp
#
# WARNING : This file will be re-generated every time a command
# to run a make target is invoked. So, any changes made to this  
# file manually, will be lost when make is invoked next. 
#################################################################

XILINX_EDK_DIR = /opt/Xilinx/latest/ISE_DS/EDK
NON_CYG_XILINX_EDK_DIR = /opt/Xilinx/latest/ISE_DS/EDK

SYSTEM = system

MHSFILE = system.mhs

MSSFILE = system.mss

FPGA_ARCH = virtex6

DEVICE = xc6vlx240tff1156-1

LANGUAGE = vhdl
GLOBAL_SEARCHPATHOPT = 
PROJECT_SEARCHPATHOPT =  -lp /home/eugene/homogeneous_port/src/hardware/

SEARCHPATHOPT = $(PROJECT_SEARCHPATHOPT) $(GLOBAL_SEARCHPATHOPT)

SUBMODULE_OPT = 

PLATGEN_OPTIONS = -p $(DEVICE) -lang $(LANGUAGE) $(SEARCHPATHOPT) $(SUBMODULE_OPT) -msg __xps/ise/xmsgprops.lst

LIBGEN_OPTIONS = -mhs $(MHSFILE) -p $(DEVICE) $(SEARCHPATHOPT) -msg __xps/ise/xmsgprops.lst \
                   $(MICROBLAZE_0_LIBG_OPT) \
                   $(MICROBLAZE_1_LIBG_OPT)

OBSERVE_PAR_OPTIONS = -error yes

CORETEST_OUTPUT_DIR = CoreTest
CORETEST_OUTPUT = $(CORETEST_OUTPUT_DIR)/executable.elf
CYG_CORETEST_OUTPUT_DIR = CoreTest
CYG_CORETEST_OUTPUT = $(CYG_CORETEST_OUTPUT_DIR)/executable.elf

MB_HWT1_OUTPUT_DIR = MB_HWT1
MB_HWT1_OUTPUT = $(MB_HWT1_OUTPUT_DIR)/executable.elf
CYG_MB_HWT1_OUTPUT_DIR = MB_HWT1
CYG_MB_HWT1_OUTPUT = $(CYG_MB_HWT1_OUTPUT_DIR)/executable.elf

MICROBLAZE_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/microblaze/mb_bootloop.elf
MICROBLAZE_BOOTLOOP_LE = $(XILINX_EDK_DIR)/sw/lib/microblaze/mb_bootloop_le.elf
PPC405_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc405/ppc_bootloop.elf
PPC440_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc440/ppc440_bootloop.elf
BOOTLOOP_DIR = bootloops

MICROBLAZE_0_BOOTLOOP = $(BOOTLOOP_DIR)/microblaze_0.elf
MICROBLAZE_0_XMDSTUB = microblaze_0/code/xmdstub.elf

MICROBLAZE_1_BOOTLOOP = $(BOOTLOOP_DIR)/microblaze_1.elf
MICROBLAZE_1_XMDSTUB = microblaze_1/code/xmdstub.elf

BRAMINIT_ELF_FILES =  $(CORETEST_OUTPUT) $(MB_HWT1_OUTPUT) 
BRAMINIT_ELF_FILE_ARGS =   -pe microblaze_0 $(CORETEST_OUTPUT)  -pe microblaze_1 $(MB_HWT1_OUTPUT) 

ALL_USER_ELF_FILES = $(CORETEST_OUTPUT) $(MB_HWT1_OUTPUT) 

SIM_CMD = vsim

BEHAVIORAL_SIM_SCRIPT = simulation/behavioral/$(SYSTEM)_setup.do

STRUCTURAL_SIM_SCRIPT = simulation/structural/$(SYSTEM)_setup.do

TIMING_SIM_SCRIPT = simulation/timing/$(SYSTEM)_setup.do

DEFAULT_SIM_SCRIPT = $(BEHAVIORAL_SIM_SCRIPT)

MIX_LANG_SIM_OPT = -mixed yes

SIMGEN_OPTIONS = -p $(DEVICE) -lang $(LANGUAGE) $(SEARCHPATHOPT) $(BRAMINIT_ELF_FILE_ARGS) $(MIX_LANG_SIM_OPT) -msg __xps/ise/xmsgprops.lst -s mti -X /opt/Xilinx/12.3/ISE_DS/ISE


LIBRARIES =  \
       microblaze_0/lib/libxil.a  \
       microblaze_1/lib/libxil.a 

LIBSCLEAN_TARGETS = microblaze_0_libsclean microblaze_1_libsclean 

PROGRAMCLEAN_TARGETS = CoreTest_programclean MB_HWT1_programclean 

CORE_STATE_DEVELOPMENT_FILES = /opt/Xilinx/latest/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/proc_common_pkg.vhd \
/opt/Xilinx/latest/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/ipif_pkg.vhd \
/opt/Xilinx/latest/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/or_muxcy.vhd \
/opt/Xilinx/latest/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/or_gate128.vhd \
/opt/Xilinx/latest/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/family_support.vhd \
/opt/Xilinx/latest/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/pselect_f.vhd \
/opt/Xilinx/latest/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/counter_f.vhd \
/opt/Xilinx/latest/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/cntr_incr_decr_addn_f.vhd \
/opt/Xilinx/latest/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/muxf_struct_f.vhd \
/opt/Xilinx/latest/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/dynshreg_f.vhd \
/opt/Xilinx/latest/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/srl_fifo_rbu_f.vhd \
/opt/Xilinx/latest/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/srl_fifo_f.vhd \
/opt/Xilinx/latest/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/proc_common_v3_00_a/hdl/vhdl/soft_reset.vhd \
/opt/Xilinx/latest/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/plbv46_slave_single_v1_01_a/hdl/vhdl/plb_address_decoder.vhd \
/opt/Xilinx/latest/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/plbv46_slave_single_v1_01_a/hdl/vhdl/plb_slave_attachment.vhd \
/opt/Xilinx/latest/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/plbv46_slave_single_v1_01_a/hdl/vhdl/plbv46_slave_single.vhd \
/opt/Xilinx/latest/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/plbv46_master_single_v1_01_a/hdl/vhdl/data_width_adapter.vhd \
/opt/Xilinx/latest/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/plbv46_master_single_v1_01_a/hdl/vhdl/data_mirror_128.vhd \
/opt/Xilinx/latest/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/plbv46_master_single_v1_01_a/hdl/vhdl/plbv46_master_single.vhd \
/opt/Xilinx/latest/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/fsl_v20_v2_11_c/hdl/vhdl/async_fifo_bram.vhd \
/opt/Xilinx/latest/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/fsl_v20_v2_11_c/hdl/vhdl/async_fifo.vhd \
/opt/Xilinx/latest/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/fsl_v20_v2_11_c/hdl/vhdl/gen_srlfifo.vhd \
/opt/Xilinx/latest/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/fsl_v20_v2_11_c/hdl/vhdl/gen_sync_bram.vhd \
/opt/Xilinx/latest/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/fsl_v20_v2_11_c/hdl/vhdl/gen_sync_dpram.vhd \
/opt/Xilinx/latest/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/fsl_v20_v2_11_c/hdl/vhdl/sync_fifo.vhd \
/opt/Xilinx/latest/ISE_DS/EDK/hw/XilinxProcessorIPLib/pcores/fsl_v20_v2_11_c/hdl/vhdl/fsl_v20.vhd \
/home/eugene/homogeneous_port/src/hardware/MyRepository/pcores/plb_cond_vars_v1_00_a/hdl/vhdl/condvar.vhd \
/home/eugene/homogeneous_port/src/hardware/MyRepository/pcores/plb_cond_vars_v1_00_a/hdl/vhdl/user_logic.vhd \
/home/eugene/homogeneous_port/src/hardware/MyRepository/pcores/plb_cond_vars_v1_00_a/hdl/vhdl/plb_cond_vars.vhd \
/home/eugene/homogeneous_port/src/hardware/MyRepository/pcores/plb_scheduler_v1_00_a/hdl/vhdl/infer_bram.vhd \
/home/eugene/homogeneous_port/src/hardware/MyRepository/pcores/plb_scheduler_v1_00_a/hdl/vhdl/parallel.vhd \
/home/eugene/homogeneous_port/src/hardware/MyRepository/pcores/plb_scheduler_v1_00_a/hdl/vhdl/user_logic.vhd \
/home/eugene/homogeneous_port/src/hardware/MyRepository/pcores/plb_scheduler_v1_00_a/hdl/vhdl/plb_scheduler.vhd \
/home/eugene/homogeneous_port/src/hardware/MyRepository/pcores/plb_sync_manager_v1_00_a/hdl/vhdl/common.vhd \
/home/eugene/homogeneous_port/src/hardware/MyRepository/pcores/plb_sync_manager_v1_00_a/hdl/vhdl/lock_fsm.vhd \
/home/eugene/homogeneous_port/src/hardware/MyRepository/pcores/plb_sync_manager_v1_00_a/hdl/vhdl/unlock_fsm.vhd \
/home/eugene/homogeneous_port/src/hardware/MyRepository/pcores/plb_sync_manager_v1_00_a/hdl/vhdl/trylock_fsm.vhd \
/home/eugene/homogeneous_port/src/hardware/MyRepository/pcores/plb_sync_manager_v1_00_a/hdl/vhdl/owner_fsm.vhd \
/home/eugene/homogeneous_port/src/hardware/MyRepository/pcores/plb_sync_manager_v1_00_a/hdl/vhdl/kind_fsm.vhd \
/home/eugene/homogeneous_port/src/hardware/MyRepository/pcores/plb_sync_manager_v1_00_a/hdl/vhdl/count_fsm.vhd \
/home/eugene/homogeneous_port/src/hardware/MyRepository/pcores/plb_sync_manager_v1_00_a/hdl/vhdl/result_fsm.vhd \
/home/eugene/homogeneous_port/src/hardware/MyRepository/pcores/plb_sync_manager_v1_00_a/hdl/vhdl/mutex_store.vhd \
/home/eugene/homogeneous_port/src/hardware/MyRepository/pcores/plb_sync_manager_v1_00_a/hdl/vhdl/thread_store.vhd \
/home/eugene/homogeneous_port/src/hardware/MyRepository/pcores/plb_sync_manager_v1_00_a/hdl/vhdl/send_store.vhd \
/home/eugene/homogeneous_port/src/hardware/MyRepository/pcores/plb_sync_manager_v1_00_a/hdl/vhdl/slave.vhd \
/home/eugene/homogeneous_port/src/hardware/MyRepository/pcores/plb_sync_manager_v1_00_a/hdl/vhdl/master.vhd \
/home/eugene/homogeneous_port/src/hardware/MyRepository/pcores/plb_sync_manager_v1_00_a/hdl/vhdl/user_logic.vhd \
/home/eugene/homogeneous_port/src/hardware/MyRepository/pcores/plb_sync_manager_v1_00_a/hdl/vhdl/plb_sync_manager.vhd \
/home/eugene/homogeneous_port/src/hardware/MyRepository/pcores/plb_thread_manager_v1_00_a/hdl/vhdl/infer_bram_dual_port.vhd \
/home/eugene/homogeneous_port/src/hardware/MyRepository/pcores/plb_thread_manager_v1_00_a/hdl/vhdl/user_logic.vhd \
/home/eugene/homogeneous_port/src/hardware/MyRepository/pcores/plb_thread_manager_v1_00_a/hdl/vhdl/plb_thread_manager.vhd \
/home/eugene/homogeneous_port/src/hardware/MyRepository/pcores/plb_hthread_reset_core_v1_00_a/hdl/vhdl/user_logic.vhd \
/home/eugene/homogeneous_port/src/hardware/MyRepository/pcores/plb_hthread_reset_core_v1_00_a/hdl/vhdl/plb_hthread_reset_core.vhd \
/home/eugene/homogeneous_port/src/hardware/MyRepository/pcores/plb_hthreads_timer_v1_00_a/hdl/vhdl/user_logic.vhd \
/home/eugene/homogeneous_port/src/hardware/MyRepository/pcores/plb_hthreads_timer_v1_00_a/hdl/vhdl/plb_hthreads_timer.vhd

WRAPPER_NGC_FILES = implementation/microblaze_0_wrapper.ngc \
implementation/ilmb_wrapper.ngc \
implementation/dlmb_wrapper.ngc \
implementation/dlmb_cntlr_wrapper.ngc \
implementation/ilmb_cntlr_wrapper.ngc \
implementation/lmb_bram_wrapper.ngc \
implementation/microblaze_1_wrapper.ngc \
implementation/mb1_bus_wrapper.ngc \
implementation/ilmb_1_wrapper.ngc \
implementation/dlmb_1_wrapper.ngc \
implementation/dlmb_cntlr_1_wrapper.ngc \
implementation/ilmb_cntlr_1_wrapper.ngc \
implementation/lmb_bram_1_wrapper.ngc \
implementation/rs232_uart_1_wrapper.ngc \
implementation/ddr3_sdram_wrapper.ngc \
implementation/extra_bram_cntlr_wrapper.ngc \
implementation/extra_bram_block_wrapper.ngc \
implementation/clock_generator_0_wrapper.ngc \
implementation/mdm_0_wrapper.ngc \
implementation/proc_sys_reset_0_wrapper.ngc \
implementation/main_bus_wrapper.ngc \
implementation/host_bus_wrapper.ngc \
implementation/vhwti_bus_wrapper.ngc \
implementation/host_core_bridge_wrapper.ngc \
implementation/mb1_core_bridge_wrapper.ngc \
implementation/host_main_bridge_wrapper.ngc \
implementation/mb1_main_bridge_wrapper.ngc \
implementation/xps_central_dma_0_wrapper.ngc \
implementation/cond_vars_wrapper.ngc \
implementation/core_bus_wrapper.ngc \
implementation/main_core_bridge_wrapper.ngc \
implementation/core_main_bridge_wrapper.ngc \
implementation/scheduler_wrapper.ngc \
implementation/sync_manager_wrapper.ngc \
implementation/thread_manager_wrapper.ngc \
implementation/plb_hthread_reset_core_0_wrapper.ngc \
implementation/main_vhwti_bridge_wrapper.ngc \
implementation/vhwti_global_cntlr1_wrapper.ngc \
implementation/vhwti_local_cntlr1_wrapper.ngc \
implementation/vhwti_bram_block1_wrapper.ngc \
implementation/plb_hthreads_timer_0_wrapper.ngc \
implementation/xps_timer_0_wrapper.ngc \
implementation/xps_intc_0_wrapper.ngc \
implementation/chipscope_plbv46_iba_0_wrapper.ngc \
implementation/chipscope_icon_0_wrapper.ngc

POSTSYN_NETLIST = implementation/$(SYSTEM).ngc

SYSTEM_BIT = implementation/$(SYSTEM).bit

DOWNLOAD_BIT = implementation/download.bit

SYSTEM_ACE = implementation/$(SYSTEM).ace

UCF_FILE = data/system.ucf

BMM_FILE = implementation/$(SYSTEM).bmm

BITGEN_UT_FILE = etc/bitgen.ut

XFLOW_OPT_FILE = etc/fast_runtime.opt
XFLOW_DEPENDENCY = __xps/xpsxflow.opt $(XFLOW_OPT_FILE)

XPLORER_DEPENDENCY = __xps/xplorer.opt
XPLORER_OPTIONS = -p $(DEVICE) -uc $(SYSTEM).ucf -bm $(SYSTEM).bmm -max_runs 7

FPGA_IMP_DEPENDENCY = $(BMM_FILE) $(POSTSYN_NETLIST) $(UCF_FILE) $(XFLOW_DEPENDENCY)

# cygwin path for windows
SDK_EXPORT_DIR = SDK/SDK_Export/hw
CYG_SDK_EXPORT_DIR = SDK/SDK_Export/hw
SYSTEM_HW_HANDOFF = $(SDK_EXPORT_DIR)/$(SYSTEM).xml
CYG_SYSTEM_HW_HANDOFF = $(CYG_SDK_EXPORT_DIR)/$(SYSTEM).xml
SYSTEM_HW_HANDOFF_BIT = $(SDK_EXPORT_DIR)/$(SYSTEM).bit
CYG_SYSTEM_HW_HANDOFF_BIT = $(CYG_SDK_EXPORT_DIR)/$(SYSTEM).bit
SYSTEM_HW_HANDOFF_BMM = $(SDK_EXPORT_DIR)/$(SYSTEM)_bd.bmm
CYG_SYSTEM_HW_HANDOFF_BMM = $(CYG_SDK_EXPORT_DIR)/$(SYSTEM)_bd.bmm
SYSTEM_HW_HANDOFF_DEP = $(CYG_SYSTEM_HW_HANDOFF) $(CYG_SYSTEM_HW_HANDOFF_BIT) $(CYG_SYSTEM_HW_HANDOFF_BMM)

#################################################################
# SOFTWARE APPLICATION CORETEST
#################################################################

CORETEST_SOURCES = CoreTest.c 

CORETEST_HEADERS = 

CORETEST_CC = mb-gcc
CORETEST_CC_SIZE = mb-size
CORETEST_CC_OPT = -O2
CORETEST_CFLAGS = 
CORETEST_CC_SEARCH = # -B
CORETEST_LIBPATH = -L./microblaze_0/lib/ # -L
CORETEST_INCLUDES = -I./microblaze_0/include/ # -I
CORETEST_LFLAGS = # -l
CORETEST_LINKER_SCRIPT = 
CORETEST_LINKER_SCRIPT_FLAG = #-T $(CORETEST_LINKER_SCRIPT) 
CORETEST_CC_DEBUG_FLAG =  -g 
CORETEST_CC_PROFILE_FLAG = # -pg
CORETEST_CC_GLOBPTR_FLAG= # -mxl-gp-opt
CORETEST_MODE = executable
CORETEST_LIBG_OPT = -$(CORETEST_MODE) microblaze_0
CORETEST_CC_INFERRED_FLAGS= -mno-xl-soft-mul -mhard-float -mxl-barrel-shift -mno-xl-soft-div -mcpu=v8.00.a 
CORETEST_CC_START_ADDR_FLAG=  # -Wl,-defsym -Wl,_TEXT_START_ADDR=
CORETEST_CC_STACK_SIZE_FLAG=  # -Wl,-defsym -Wl,_STACK_SIZE=
CORETEST_CC_HEAP_SIZE_FLAG=  # -Wl,-defsym -Wl,_HEAP_SIZE=
CORETEST_OTHER_CC_FLAGS= $(CORETEST_CC_GLOBPTR_FLAG)  \
                  $(CORETEST_CC_START_ADDR_FLAG) $(CORETEST_CC_STACK_SIZE_FLAG) $(CORETEST_CC_HEAP_SIZE_FLAG)  \
                  $(CORETEST_CC_INFERRED_FLAGS)  \
                  $(CORETEST_LINKER_SCRIPT_FLAG) $(CORETEST_CC_DEBUG_FLAG) $(CORETEST_CC_PROFILE_FLAG) 

#################################################################
# SOFTWARE APPLICATION MB_HWT1
#################################################################

MB_HWT1_SOURCES = my_sw/hw_thread.c my_sw/proc_hw_thread.c 

MB_HWT1_HEADERS = my_sw/proc_hw_thread.h 

MB_HWT1_CC = mb-gcc
MB_HWT1_CC_SIZE = mb-size
MB_HWT1_CC_OPT = -O2
MB_HWT1_CFLAGS = 
MB_HWT1_CC_SEARCH = # -B
MB_HWT1_LIBPATH = -L./microblaze_1/lib/ # -L
MB_HWT1_INCLUDES = -I./microblaze_1/include/  -Imy_sw/ # -I
MB_HWT1_LFLAGS = # -l
MB_HWT1_LINKER_SCRIPT = 
MB_HWT1_LINKER_SCRIPT_FLAG = #-T $(MB_HWT1_LINKER_SCRIPT) 
MB_HWT1_CC_DEBUG_FLAG =  -g 
MB_HWT1_CC_PROFILE_FLAG = # -pg
MB_HWT1_CC_GLOBPTR_FLAG= # -mxl-gp-opt
MB_HWT1_MODE = executable
MB_HWT1_LIBG_OPT = -$(MB_HWT1_MODE) microblaze_1
MB_HWT1_CC_INFERRED_FLAGS= -mno-xl-soft-mul -mhard-float -mxl-barrel-shift -mno-xl-soft-div -mcpu=v8.00.a 
MB_HWT1_CC_START_ADDR_FLAG=  # -Wl,-defsym -Wl,_TEXT_START_ADDR=
MB_HWT1_CC_STACK_SIZE_FLAG=  # -Wl,-defsym -Wl,_STACK_SIZE=
MB_HWT1_CC_HEAP_SIZE_FLAG=  # -Wl,-defsym -Wl,_HEAP_SIZE=
MB_HWT1_OTHER_CC_FLAGS= $(MB_HWT1_CC_GLOBPTR_FLAG)  \
                  $(MB_HWT1_CC_START_ADDR_FLAG) $(MB_HWT1_CC_STACK_SIZE_FLAG) $(MB_HWT1_CC_HEAP_SIZE_FLAG)  \
                  $(MB_HWT1_CC_INFERRED_FLAGS)  \
                  $(MB_HWT1_LINKER_SCRIPT_FLAG) $(MB_HWT1_CC_DEBUG_FLAG) $(MB_HWT1_CC_PROFILE_FLAG) 
