onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -divider {Master Logic}
add wave -noupdate -format Logic /testbench/synch/master_logic_i/bus2ip_clk
add wave -noupdate -format Logic /testbench/synch/master_logic_i/bus2ip_reset
add wave -noupdate -format Literal /testbench/synch/master_logic_i/bus2ip_addr
add wave -noupdate -format Literal /testbench/synch/master_logic_i/bus2ip_data
add wave -noupdate -format Literal /testbench/synch/master_logic_i/bus2ip_be
add wave -noupdate -format Logic /testbench/synch/master_logic_i/bus2ip_rnw
add wave -noupdate -format Literal /testbench/synch/master_logic_i/bus2ip_rdce
add wave -noupdate -format Literal /testbench/synch/master_logic_i/bus2ip_wrce
add wave -noupdate -format Logic /testbench/synch/master_logic_i/bus2ip_rdreq
add wave -noupdate -format Logic /testbench/synch/master_logic_i/bus2ip_wrreq
add wave -noupdate -format Logic /testbench/synch/master_logic_i/bus2ip_msterror
add wave -noupdate -format Logic /testbench/synch/master_logic_i/bus2ip_mstlastack
add wave -noupdate -format Logic /testbench/synch/master_logic_i/bus2ip_mstrdack
add wave -noupdate -format Logic /testbench/synch/master_logic_i/bus2ip_mstwrack
add wave -noupdate -format Logic /testbench/synch/master_logic_i/bus2ip_mstretry
add wave -noupdate -format Logic /testbench/synch/master_logic_i/bus2ip_msttimeout
add wave -noupdate -format Literal /testbench/synch/master_logic_i/ip2bus_addr
add wave -noupdate -format Literal /testbench/synch/master_logic_i/ip2bus_mstbe
add wave -noupdate -format Logic /testbench/synch/master_logic_i/ip2bus_mstburst
add wave -noupdate -format Logic /testbench/synch/master_logic_i/ip2bus_mstbuslock
add wave -noupdate -format Logic /testbench/synch/master_logic_i/ip2bus_mstrdreq
add wave -noupdate -format Logic /testbench/synch/master_logic_i/ip2bus_mstwrreq
add wave -noupdate -format Literal /testbench/synch/master_logic_i/ip2ip_addr
add wave -noupdate -format Logic /testbench/synch/master_logic_i/send_ena
add wave -noupdate -format Literal /testbench/synch/master_logic_i/send_id
add wave -noupdate -format Logic /testbench/synch/master_logic_i/send_ack
add wave -noupdate -format Literal /testbench/synch/master_logic_i/send_cs
add wave -noupdate -format Literal /testbench/synch/master_logic_i/send_ns
add wave -noupdate -format Literal /testbench/synch/master_logic_i/send_tid
add wave -noupdate -format Literal /testbench/synch/master_logic_i/send_nxt
add wave -noupdate -divider {Slave Logic}
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/c_num_threads
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/c_num_mutexes
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/c_awidth
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/c_dwidth
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/c_max_ar_dwidth
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/c_num_addr_rng
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/c_num_ce
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/bus2ip_clk
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/bus2ip_reset
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/system_reset
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/system_resetdone
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/bus2ip_addr
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/bus2ip_data
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/bus2ip_be
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/bus2ip_rnw
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/bus2ip_rdce
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/bus2ip_wrce
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/bus2ip_rdreq
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/bus2ip_wrreq
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/ip2bus_data
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/ip2bus_retry
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/ip2bus_error
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/ip2bus_toutsup
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/ip2bus_rdack
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/ip2bus_wrack
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/bus2ip_ardata
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/bus2ip_arbe
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/bus2ip_arcs
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/ip2bus_ardata
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/send_ena
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/send_id
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/send_ack
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/clk
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/rst
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/rnw
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/datain
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/lock_finish
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/unlock_finish
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/trylock_finish
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/count_finish
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/kind_finish
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/owner_finish
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/result_finish
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/lock_data
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/unlock_data
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/trylock_data
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/count_data
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/kind_data
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/owner_data
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/result_data
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/lock_maddr
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/unlock_maddr
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/trylock_maddr
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/count_maddr
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/kind_maddr
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/owner_maddr
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/lock_mena
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/unlock_mena
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/trylock_mena
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/count_mena
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/kind_mena
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/owner_mena
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/lock_mwea
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/unlock_mwea
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/trylock_mwea
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/count_mwea
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/kind_mwea
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/owner_mwea
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/lock_mowner
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/unlock_mowner
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/trylock_mowner
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/count_mowner
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/kind_mowner
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/owner_mowner
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/lock_mlast
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/unlock_mlast
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/trylock_mlast
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/count_mlast
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/kind_mlast
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/owner_mlast
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/lock_mcount
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/unlock_mcount
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/trylock_mcount
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/count_mcount
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/kind_mcount
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/owner_mcount
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/lock_mkind
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/unlock_mkind
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/trylock_mkind
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/count_mkind
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/kind_mkind
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/owner_mkind
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/lock_taddr
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/unlock_taddr
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/trylock_taddr
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/count_taddr
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/kind_taddr
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/owner_taddr
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/lock_tena
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/unlock_tena
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/trylock_tena
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/count_tena
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/kind_tena
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/owner_tena
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/lock_twea
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/unlock_twea
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/trylock_twea
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/count_twea
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/kind_twea
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/owner_twea
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/lock_tnext
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/unlock_tnext
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/trylock_tnext
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/count_tnext
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/kind_tnext
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/owner_tnext
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/unlock_sena
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/unlock_sid
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/miaddr
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/miena
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/miwea
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/miowner
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/milast
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/micount
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/mikind
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/moowner
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/molast
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/mocount
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/mokind
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/tiaddr
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/tiena
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/tiwea
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/tinext
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/tonext
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/cmd_number
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/thr_number
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/mtx_number
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/knd_number
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/result_start
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/kind_start
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/count_start
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/owner_start
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/trylock_start
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/unlock_start
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/lock_start
add wave -noupdate -divider {Lock FSM}
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/lock_i/clk
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/lock_i/rst
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/lock_i/sysrst
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/lock_i/rstdone
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/lock_i/start
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/lock_i/finish
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/lock_i/data
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/lock_i/mutex
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/lock_i/thread
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/lock_i/miowner
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/lock_i/milast
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/lock_i/micount
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/lock_i/mikind
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/lock_i/tinext
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/lock_i/moaddr
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/lock_i/moena
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/lock_i/mowea
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/lock_i/moowner
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/lock_i/molast
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/lock_i/mocount
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/lock_i/mokind
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/lock_i/toaddr
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/lock_i/toena
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/lock_i/towea
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/lock_i/tonext
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/lock_i/lock_cs
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/lock_i/lock_ns
add wave -noupdate -divider {Unlock FSM}
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/unlock_i/clk
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/unlock_i/rst
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/unlock_i/sysrst
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/unlock_i/rstdone
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/unlock_i/start
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/unlock_i/finish
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/unlock_i/data
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/unlock_i/mutex
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/unlock_i/thread
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/unlock_i/miowner
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/unlock_i/milast
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/unlock_i/micount
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/unlock_i/mikind
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/unlock_i/tinext
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/unlock_i/moaddr
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/unlock_i/moena
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/unlock_i/mowea
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/unlock_i/moowner
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/unlock_i/molast
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/unlock_i/mocount
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/unlock_i/mokind
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/unlock_i/toaddr
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/unlock_i/toena
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/unlock_i/towea
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/unlock_i/tonext
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/unlock_i/sena
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/unlock_i/sid
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/unlock_i/sack
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/unlock_i/unlock_cs
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/unlock_i/unlock_ns
add wave -noupdate -divider {Try Lock FSM}
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/trylock_i/clk
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/trylock_i/rst
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/trylock_i/sysrst
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/trylock_i/rstdone
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/trylock_i/start
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/trylock_i/finish
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/trylock_i/data
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/trylock_i/mutex
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/trylock_i/thread
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/trylock_i/miowner
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/trylock_i/milast
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/trylock_i/micount
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/trylock_i/mikind
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/trylock_i/tinext
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/trylock_i/moaddr
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/trylock_i/moena
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/trylock_i/mowea
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/trylock_i/moowner
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/trylock_i/molast
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/trylock_i/mocount
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/trylock_i/mokind
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/trylock_i/toaddr
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/trylock_i/toena
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/trylock_i/towea
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/trylock_i/tonext
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/trylock_i/try_cs
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/trylock_i/try_ns
add wave -noupdate -divider {Count FSM}
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/count_i/clk
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/count_i/rst
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/count_i/sysrst
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/count_i/rstdone
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/count_i/start
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/count_i/finish
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/count_i/data
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/count_i/mutex
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/count_i/thread
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/count_i/miowner
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/count_i/milast
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/count_i/micount
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/count_i/mikind
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/count_i/tinext
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/count_i/moaddr
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/count_i/moena
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/count_i/mowea
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/count_i/moowner
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/count_i/molast
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/count_i/mocount
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/count_i/mokind
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/count_i/toaddr
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/count_i/toena
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/count_i/towea
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/count_i/tonext
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/count_i/count_cs
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/count_i/count_ns
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/count_i/cdata
add wave -noupdate -divider {Kind FSM}
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/kind_i/clk
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/kind_i/rst
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/kind_i/sysrst
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/kind_i/rstdone
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/kind_i/start
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/kind_i/finish
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/kind_i/rnw
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/kind_i/datain
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/kind_i/data
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/kind_i/mutex
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/kind_i/thread
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/kind_i/miowner
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/kind_i/milast
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/kind_i/micount
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/kind_i/mikind
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/kind_i/tinext
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/kind_i/moaddr
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/kind_i/moena
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/kind_i/mowea
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/kind_i/moowner
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/kind_i/molast
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/kind_i/mocount
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/kind_i/mokind
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/kind_i/toaddr
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/kind_i/toena
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/kind_i/towea
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/kind_i/tonext
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/kind_i/kind_cs
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/kind_i/kind_ns
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/kind_i/kodata
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/kind_i/kidata
add wave -noupdate -divider {Owner FSM}
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/owner_i/clk
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/owner_i/rst
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/owner_i/sysrst
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/owner_i/rstdone
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/owner_i/start
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/owner_i/finish
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/owner_i/data
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/owner_i/mutex
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/owner_i/thread
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/owner_i/miowner
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/owner_i/milast
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/owner_i/micount
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/owner_i/mikind
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/owner_i/tinext
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/owner_i/moaddr
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/owner_i/moena
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/owner_i/mowea
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/owner_i/moowner
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/owner_i/molast
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/owner_i/mocount
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/owner_i/mokind
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/owner_i/toaddr
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/owner_i/toena
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/owner_i/towea
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/owner_i/tonext
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/owner_i/owner_cs
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/owner_i/owner_ns
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/owner_i/odata
add wave -noupdate -divider {Result FSM}
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/result_i/clk
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/result_i/rst
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/result_i/sysrst
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/result_i/rstdone
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/result_i/start
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/result_i/finish
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/result_i/rnw
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/result_i/datain
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/result_i/data
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/result_i/results
add wave -noupdate -divider {Mutex Store}
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/mutex_i/clk
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/mutex_i/rst
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/mutex_i/sysrst
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/mutex_i/rstdone
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/mutex_i/miaddr
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/mutex_i/miena
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/mutex_i/miwea
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/mutex_i/miowner
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/mutex_i/milast
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/mutex_i/mikind
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/mutex_i/micount
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/mutex_i/moowner
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/mutex_i/molast
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/mutex_i/mokind
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/mutex_i/mocount
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/mutex_i/store
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/mutex_i/minput
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/mutex_i/moutput
add wave -noupdate -divider {Thread Store}
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/thread_i/clk
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/thread_i/rst
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/thread_i/sysrst
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/thread_i/rstdone
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/thread_i/tiaddr
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/thread_i/tiena
add wave -noupdate -format Logic /testbench/synch/slave_logic_i/thread_i/tiwea
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/thread_i/tinext
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/thread_i/tonext
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/thread_i/store
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/thread_i/tinput
add wave -noupdate -format Literal /testbench/synch/slave_logic_i/thread_i/toutput
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {57 ns} 0}
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
update
WaveRestoreZoom {0 ns} {1 us}
