thread_create( &tid[5], &attr[5], histogram_thread_FUNC_ID, (void*)(&thread_arg[0]),DYNAMIC_HW,0 );
thread_create( &tid[6], &attr[6], histogram_thread_FUNC_ID, (void*)(&thread_arg[1]),DYNAMIC_HW,0 );
thread_create( &tid[7], &attr[7], histogram_thread_FUNC_ID, (void*)(&thread_arg[2]),DYNAMIC_HW,0 );
thread_create( &tid[8], &attr[8], histogram_thread_FUNC_ID, (void*)(&thread_arg[3]),DYNAMIC_HW,0 );
thread_create( &tid[9], &attr[9], histogram_thread_FUNC_ID, (void*)(&thread_arg[4]),DYNAMIC_HW,0 );
thread_create( &tid[16], &attr[16], matrix_mult_thread_FUNC_ID, (void *) &matrix_arg[3], DYNAMIC_HW, 0);
thread_create( &tid[13], &attr[13], matrix_mult_thread_FUNC_ID, (void *) &matrix_arg[0], DYNAMIC_HW, 0);
thread_create(&tid[2], &attr[2], pi_thread_FUNC_ID, (void *) &thread_data[2], DYNAMIC_HW, 0);
//thread_create(&tid[23], &attr[23], mandel_thread_FUNC_ID, (void *) MANDEL_MAX_ITERATIONS, DYNAMIC_HW, 0);
thread_create( &tid[18], &attr[18], find_max_thread_FUNC_ID, (void *) &findmax_arg[1], DYNAMIC_HW, 0);
thread_create( &tid[21], &attr[21], find_max_thread_FUNC_ID, (void *) &findmax_arg[4], DYNAMIC_HW, 0);
thread_create( &tid[14], &attr[14], matrix_mult_thread_FUNC_ID, (void *) &matrix_arg[1], DYNAMIC_HW, 0);
thread_create( &tid[11], &attr[12], distance_thread_FUNC_ID, (void *) &distance_arg[1], DYNAMIC_HW, 0);
//thread_create(&tid[24], &attr[24], mandel_thread_FUNC_ID, (void *) MANDEL_MAX_ITERATIONS, DYNAMIC_HW, 0);
thread_create(&tid[1], &attr[1], pi_thread_FUNC_ID, (void *) &thread_data[1], DYNAMIC_HW, 0);
thread_create(&tid[4], &attr[4], pi_thread_FUNC_ID, (void *) &thread_data[4], DYNAMIC_HW, 0);
thread_create( &tid[12], &attr[11], distance_thread_FUNC_ID, (void *) &distance_arg[2], DYNAMIC_HW, 0);
thread_create( &tid[15], &attr[15], matrix_mult_thread_FUNC_ID, (void *) &matrix_arg[2], DYNAMIC_HW, 0);
thread_create( &tid[17], &attr[17], find_max_thread_FUNC_ID, (void *) &findmax_arg[0], DYNAMIC_HW, 0);
thread_create(&tid[3], &attr[3], pi_thread_FUNC_ID, (void *) &thread_data[3], DYNAMIC_HW, 0);
thread_create(&tid[0], &attr[0], pi_thread_FUNC_ID, (void *) &thread_data[0], DYNAMIC_HW, 0);
thread_create( &tid[10], &attr[10], distance_thread_FUNC_ID, (void *) &distance_arg[0], DYNAMIC_HW, 0);
thread_create( &tid[20], &attr[20], find_max_thread_FUNC_ID, (void *) &findmax_arg[3], DYNAMIC_HW, 0);
//thread_create(&tid[22], &attr[22], mandel_thread_FUNC_ID, (void *) MANDEL_MAX_ITERATIONS, DYNAMIC_HW, 0);
thread_create( &tid[19], &attr[19], find_max_thread_FUNC_ID, (void *) &findmax_arg[2], DYNAMIC_HW, 0);
