# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1761-2
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
set_property ip_repo_paths {
  /home/abazar63/hthread/src/hardware/MyRepository/pcores/axi_hthread_cores
  /home/abazar63/hthread/src/hardware/MyRepository/pcores/vivado_cores
  /home/abazar63/hthread/src/hardware/MyRepository/pcores/vivado_cores/hdl_crc_v1_00_a
} [current_fileset]
read_vhdl -library xil_defaultlib {
  /home/abazar63/hthread/src/hardware/MyRepository/pcores/vivado_cores/hdl_crc_v1_00_a/hdl/user_logic_hwtul.vhd
  /home/abazar63/hthread/src/hardware/MyRepository/pcores/vivado_cores/hdl_crc_v1_00_a/hdl/hdl_crc.vhd
}
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/abazar63/hthread/src/hardware/MyRepository/pcores/vivado_cores/hdl_crc_v1_00_a/hdl_crc_v1_0_project/hdl_crc_v1_0_project.cache/wt [current_project]
set_property parent.project_dir /home/abazar63/hthread/src/hardware/MyRepository/pcores/vivado_cores/hdl_crc_v1_00_a/hdl_crc_v1_0_project [current_project]
catch { write_hwdef -file hdl_crc.hwdef }
synth_design -top hdl_crc -part xc7vx485tffg1761-2
write_checkpoint hdl_crc.dcp
report_utilization -file hdl_crc_utilization_synth.rpt -pb hdl_crc_utilization_synth.pb
