# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1761-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/abazar63/hthread/src/hardware/MyRepository/pcores/axi_hthread_cores/axi_hthreads_timer_v1_00_a/managed_ip_project/axi_hthreads_timer_v1_0_project/axi_hthreads_timer_v1_0_project.cache/wt [current_project]
set_property parent.project_path /home/abazar63/hthread/src/hardware/MyRepository/pcores/axi_hthread_cores/axi_hthreads_timer_v1_00_a/managed_ip_project/axi_hthreads_timer_v1_0_project/axi_hthreads_timer_v1_0_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  /home/abazar63/hthread/src/hardware/MyRepository/pcores/axi_hthread_cores
  /home/abazar63/hthread/src/hardware/MyRepository/pcores/vivado_cores
} [current_project]
read_vhdl -library proc_common_v3_00_a {
  /home/abazar63/hthread/src/hardware/MyRepository/pcores/axi_hthread_cores/proc_common_v3_00_a/hdl/vhdl/proc_common_pkg.vhd
  /home/abazar63/hthread/src/hardware/MyRepository/pcores/axi_hthread_cores/proc_common_v3_00_a/hdl/vhdl/family_support.vhd
  /home/abazar63/hthread/src/hardware/MyRepository/pcores/axi_hthread_cores/proc_common_v3_00_a/hdl/vhdl/pselect_f.vhd
  /home/abazar63/hthread/src/hardware/MyRepository/pcores/axi_hthread_cores/proc_common_v3_00_a/hdl/vhdl/ipif_pkg.vhd
  /home/abazar63/hthread/src/hardware/MyRepository/pcores/axi_hthread_cores/proc_common_v3_00_a/hdl/vhdl/counter_f.vhd
  /home/abazar63/hthread/src/hardware/MyRepository/pcores/axi_hthread_cores/proc_common_v3_00_a/hdl/vhdl/soft_reset.vhd
}
read_vhdl -library axi_lite_ipif_v1_01_a {
  /home/abazar63/hthread/src/hardware/MyRepository/pcores/axi_hthread_cores/axi_lite_ipif_v1_01_a/hdl/vhdl/address_decoder.vhd
  /home/abazar63/hthread/src/hardware/MyRepository/pcores/axi_hthread_cores/axi_lite_ipif_v1_01_a/hdl/vhdl/slave_attachment.vhd
  /home/abazar63/hthread/src/hardware/MyRepository/pcores/axi_hthread_cores/axi_lite_ipif_v1_01_a/hdl/vhdl/axi_lite_ipif.vhd
}
read_vhdl -library axi_hthreads_timer_v1_00_a {
  /home/abazar63/hthread/src/hardware/MyRepository/pcores/axi_hthread_cores/axi_hthreads_timer_v1_00_a/hdl/vhdl/user_logic.vhd
  /home/abazar63/hthread/src/hardware/MyRepository/pcores/axi_hthread_cores/axi_hthreads_timer_v1_00_a/hdl/vhdl/axi_hthreads_timer.vhd
}
synth_design -top axi_hthreads_timer -part xc7vx485tffg1761-2
write_checkpoint -noxdef axi_hthreads_timer.dcp
catch { report_utilization -file axi_hthreads_timer_utilization_synth.rpt -pb axi_hthreads_timer_utilization_synth.pb }
