
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 9.1.02 EDK_J_SP2.4
* DO NOT EDIT.
*
* Copyright (c) 2005 Xilinx, Inc.  All rights reserved. 
* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xemac.h"

/*
* The configuration table for devices
*/

XEmac_Config XEmac_ConfigTable[] =
{
	{
		XPAR_ETHERNET_MAC_DEVICE_ID,
		XPAR_ETHERNET_MAC_BASEADDR,
		XPAR_ETHERNET_MAC_ERR_COUNT_EXIST,
		XPAR_ETHERNET_MAC_DMA_PRESENT,
		XPAR_ETHERNET_MAC_MII_EXIST
	}
};


