#################################################################
# Makefile generated by Xilinx Platform Studio 
# Project:/home/jagron/uark_research/uark_ht_trunk/src/platforms/xilinx/ml507_icache_shared_data/design/system.xmp
#
# WARNING : This file will be re-generated every time a command
# to run a make target is invoked. So, any changes made to this  
# file manually, will be lost when make is invoked next. 
#################################################################

# Name of the Microprocessor system
# The hardware specification of the system is in file :
# /home/jagron/uark_research/uark_ht_trunk/src/platforms/xilinx/ml507_icache_shared_data/design/system.mhs
# The software specification of the system is in file :
# /home/jagron/uark_research/uark_ht_trunk/src/platforms/xilinx/ml507_icache_shared_data/design/system.mss

include system_incl.make

#################################################################
# PHONY TARGETS
#################################################################
.PHONY: dummy
.PHONY: netlistclean
.PHONY: bitsclean
.PHONY: simclean
.PHONY: vpclean

#################################################################
# EXTERNAL TARGETS
#################################################################
all:
	@echo "Makefile to build a Microprocessor system :"
	@echo "Run make with any of the following targets"
	@echo " "
	@echo "  netlist  : Generates the netlist for the given MHS "
	@echo "  bits     : Runs Implementation tools to generate the bitstream"
	@echo " "
	@echo "  libs     : Configures the sw libraries for this system"
	@echo "  program  : Compiles the program sources for all the processor instances"
	@echo " "
	@echo "  init_bram: Initializes bitstream with BRAM data"
	@echo "  ace      : Generate ace file from bitstream and elf"
	@echo "  download : Downloads the bitstream onto the board"
	@echo " "
	@echo "  sim      : Generates HDL simulation models and runs simulator for chosen simulation mode"
	@echo "  simmodel : Generates HDL simulation models for chosen simulation mode"
	@echo "  behavioral_model : Generates behavioral HDL models with BRAM initialization"
	@echo "  structural_model : Generates structural simulation HDL models with BRAM initialization"
	@echo "  timing   : Generates timing simulation HDL models with BRAM initialization"
	@echo "  vp       : Generates virtual platform model"
	@echo " "
	@echo "  netlistclean: Deletes netlist"
	@echo "  bitsclean: Deletes bit, ncd, bmm files"
	@echo "  hwclean  : Deletes implementation dir"
	@echo "  libsclean: Deletes sw libraries"
	@echo "  programclean: Deletes compiled ELF files"
	@echo "  swclean  : Deletes sw libraries and ELF files"
	@echo "  simclean : Deletes simulation dir"
	@echo "  vpclean  : Deletes virtualplatform dir"
	@echo "  clean    : Deletes all generated files/directories"
	@echo " "
	@echo "  make <target> : (Default)"
	@echo "      Creates a Microprocessor system using default initializations"
	@echo "      specified for each processor in MSS file"


bits: $(SYSTEM_BIT)

ace: $(SYSTEM_ACE)

netlist: $(POSTSYN_NETLIST)

libs: $(LIBRARIES)

program: $(ALL_USER_ELF_FILES)

download: $(DOWNLOAD_BIT) dummy
	@echo "*********************************************"
	@echo "Downloading Bitstream onto the target board"
	@echo "*********************************************"
	impact -batch etc/download.cmd

init_bram: $(DOWNLOAD_BIT)

sim: $(DEFAULT_SIM_SCRIPT)
	cd simulation/behavioral; \
	$(SIM_CMD)  &

simmodel: $(DEFAULT_SIM_SCRIPT)

behavioral_model: $(BEHAVIORAL_SIM_SCRIPT)

structural_model: $(STRUCTURAL_SIM_SCRIPT)

vp: $(VPEXEC)

clean: hwclean libsclean programclean simclean vpclean
	rm -f _impact.cmd
	rm -f *.log

hwclean: netlistclean bitsclean
	rm -rf implementation synthesis xst hdl
	rm -rf xst.srp $(SYSTEM).srp

netlistclean:
	rm -f $(POSTSYN_NETLIST)
	rm -f platgen.log
	rm -f $(BMM_FILE)

bitsclean:
	rm -f $(SYSTEM_BIT)
	rm -f implementation/$(SYSTEM).ncd
	rm -f implementation/$(SYSTEM)_bd.bmm 
	rm -f implementation/$(SYSTEM)_map.ncd 
	rm -f __xps/$(SYSTEM)_routed

simclean: 
	rm -rf simulation/behavioral
	rm -f simgen.log

swclean: libsclean programclean
	@echo ""

libsclean: $(LIBSCLEAN_TARGETS)
	rm -f libgen.log

programclean: $(PROGRAMCLEAN_TARGETS)

vpclean:
	rm -rf virtualplatform
	rm -f vpgen.log

#################################################################
# SOFTWARE PLATFORM FLOW
#################################################################


$(LIBRARIES): $(MHSFILE) $(MSSFILE) __xps/libgen.opt
	@echo "*********************************************"
	@echo "Creating software libraries..."
	@echo "*********************************************"
	libgen $(LIBGEN_OPTIONS) $(MSSFILE)


ppc440_0_libsclean:
	rm -rf ppc440_0/

microblaze_0_libsclean:
	rm -rf microblaze_0/

microblaze_1_libsclean:
	rm -rf microblaze_1/

microblaze_2_libsclean:
	rm -rf microblaze_2/

microblaze_mb3_libsclean:
	rm -rf microblaze_mb3/

microblaze_mb4_libsclean:
	rm -rf microblaze_mb4/

microblaze_mb5_libsclean:
	rm -rf microblaze_mb5/

#################################################################
# SOFTWARE APPLICATION TESTAPP_MEMORY
#################################################################

TestApp_Memory_program: $(TESTAPP_MEMORY_OUTPUT) 

$(TESTAPP_MEMORY_OUTPUT) : $(TESTAPP_MEMORY_SOURCES) $(TESTAPP_MEMORY_HEADERS) $(TESTAPP_MEMORY_LINKER_SCRIPT) \
                    $(LIBRARIES) __xps/testapp_memory_compiler.opt
	@mkdir -p $(TESTAPP_MEMORY_OUTPUT_DIR) 
	$(TESTAPP_MEMORY_CC) $(TESTAPP_MEMORY_CC_OPT) $(TESTAPP_MEMORY_SOURCES) -o $(TESTAPP_MEMORY_OUTPUT) \
	$(TESTAPP_MEMORY_OTHER_CC_FLAGS) $(TESTAPP_MEMORY_INCLUDES) $(TESTAPP_MEMORY_LIBPATH) \
	$(TESTAPP_MEMORY_CFLAGS) $(TESTAPP_MEMORY_LFLAGS) 
	$(TESTAPP_MEMORY_CC_SIZE) $(TESTAPP_MEMORY_OUTPUT) 
	@echo ""

TestApp_Memory_programclean:
	rm -f $(TESTAPP_MEMORY_OUTPUT) 

#################################################################
# SOFTWARE APPLICATION TESTAPP_PERIPHERAL
#################################################################

TestApp_Peripheral_program: $(TESTAPP_PERIPHERAL_OUTPUT) 

$(TESTAPP_PERIPHERAL_OUTPUT) : $(TESTAPP_PERIPHERAL_SOURCES) $(TESTAPP_PERIPHERAL_HEADERS) $(TESTAPP_PERIPHERAL_LINKER_SCRIPT) \
                    $(LIBRARIES) __xps/testapp_peripheral_compiler.opt
	@mkdir -p $(TESTAPP_PERIPHERAL_OUTPUT_DIR) 
	$(TESTAPP_PERIPHERAL_CC) $(TESTAPP_PERIPHERAL_CC_OPT) $(TESTAPP_PERIPHERAL_SOURCES) -o $(TESTAPP_PERIPHERAL_OUTPUT) \
	$(TESTAPP_PERIPHERAL_OTHER_CC_FLAGS) $(TESTAPP_PERIPHERAL_INCLUDES) $(TESTAPP_PERIPHERAL_LIBPATH) \
	$(TESTAPP_PERIPHERAL_CFLAGS) $(TESTAPP_PERIPHERAL_LFLAGS) 
	$(TESTAPP_PERIPHERAL_CC_SIZE) $(TESTAPP_PERIPHERAL_OUTPUT) 
	@echo ""

TestApp_Peripheral_programclean:
	rm -f $(TESTAPP_PERIPHERAL_OUTPUT) 

#################################################################
# SOFTWARE APPLICATION MB_HWT
#################################################################

MB_HWT_program: $(MB_HWT_OUTPUT) 

$(MB_HWT_OUTPUT) : $(MB_HWT_SOURCES) $(MB_HWT_HEADERS) $(MB_HWT_LINKER_SCRIPT) \
                    $(LIBRARIES) __xps/mb_hwt_compiler.opt
	@mkdir -p $(MB_HWT_OUTPUT_DIR) 
	$(MB_HWT_CC) $(MB_HWT_CC_OPT) $(MB_HWT_SOURCES) -o $(MB_HWT_OUTPUT) \
	$(MB_HWT_OTHER_CC_FLAGS) $(MB_HWT_INCLUDES) $(MB_HWT_LIBPATH) \
	$(MB_HWT_CFLAGS) $(MB_HWT_LFLAGS) 
	$(MB_HWT_CC_SIZE) $(MB_HWT_OUTPUT) 
	@echo ""

MB_HWT_programclean:
	rm -f $(MB_HWT_OUTPUT) 

#################################################################
# SOFTWARE APPLICATION EMBEDDABLE
#################################################################

embeddable_program: $(EMBEDDABLE_OUTPUT) 

$(EMBEDDABLE_OUTPUT) : $(EMBEDDABLE_SOURCES) $(EMBEDDABLE_HEADERS) $(EMBEDDABLE_LINKER_SCRIPT) \
                    $(LIBRARIES) __xps/embeddable_compiler.opt
	@mkdir -p $(EMBEDDABLE_OUTPUT_DIR) 
	$(EMBEDDABLE_CC) $(EMBEDDABLE_CC_OPT) $(EMBEDDABLE_SOURCES) -o $(EMBEDDABLE_OUTPUT) \
	$(EMBEDDABLE_OTHER_CC_FLAGS) $(EMBEDDABLE_INCLUDES) $(EMBEDDABLE_LIBPATH) \
	$(EMBEDDABLE_CFLAGS) $(EMBEDDABLE_LFLAGS) 
	$(EMBEDDABLE_CC_SIZE) $(EMBEDDABLE_OUTPUT) 
	@echo ""

embeddable_programclean:
	rm -f $(EMBEDDABLE_OUTPUT) 

#################################################################
# SOFTWARE APPLICATION MB_HWT1
#################################################################

MB_HWT1_program: $(MB_HWT1_OUTPUT) 

$(MB_HWT1_OUTPUT) : $(MB_HWT1_SOURCES) $(MB_HWT1_HEADERS) $(MB_HWT1_LINKER_SCRIPT) \
                    $(LIBRARIES) __xps/mb_hwt1_compiler.opt
	@mkdir -p $(MB_HWT1_OUTPUT_DIR) 
	$(MB_HWT1_CC) $(MB_HWT1_CC_OPT) $(MB_HWT1_SOURCES) -o $(MB_HWT1_OUTPUT) \
	$(MB_HWT1_OTHER_CC_FLAGS) $(MB_HWT1_INCLUDES) $(MB_HWT1_LIBPATH) \
	$(MB_HWT1_CFLAGS) $(MB_HWT1_LFLAGS) 
	$(MB_HWT1_CC_SIZE) $(MB_HWT1_OUTPUT) 
	@echo ""

MB_HWT1_programclean:
	rm -f $(MB_HWT1_OUTPUT) 

#################################################################
# SOFTWARE APPLICATION EMBEDDABLE_COMPAT
#################################################################

embeddable_compat_program: $(EMBEDDABLE_COMPAT_OUTPUT) 

$(EMBEDDABLE_COMPAT_OUTPUT) : $(EMBEDDABLE_COMPAT_SOURCES) $(EMBEDDABLE_COMPAT_HEADERS) $(EMBEDDABLE_COMPAT_LINKER_SCRIPT) \
                    $(LIBRARIES) __xps/embeddable_compat_compiler.opt
	@mkdir -p $(EMBEDDABLE_COMPAT_OUTPUT_DIR) 
	$(EMBEDDABLE_COMPAT_CC) $(EMBEDDABLE_COMPAT_CC_OPT) $(EMBEDDABLE_COMPAT_SOURCES) -o $(EMBEDDABLE_COMPAT_OUTPUT) \
	$(EMBEDDABLE_COMPAT_OTHER_CC_FLAGS) $(EMBEDDABLE_COMPAT_INCLUDES) $(EMBEDDABLE_COMPAT_LIBPATH) \
	$(EMBEDDABLE_COMPAT_CFLAGS) $(EMBEDDABLE_COMPAT_LFLAGS) 
	$(EMBEDDABLE_COMPAT_CC_SIZE) $(EMBEDDABLE_COMPAT_OUTPUT) 
	@echo ""

embeddable_compat_programclean:
	rm -f $(EMBEDDABLE_COMPAT_OUTPUT) 

#################################################################
# SOFTWARE APPLICATION MB_HWT2
#################################################################

MB_HWT2_program: $(MB_HWT2_OUTPUT) 

$(MB_HWT2_OUTPUT) : $(MB_HWT2_SOURCES) $(MB_HWT2_HEADERS) $(MB_HWT2_LINKER_SCRIPT) \
                    $(LIBRARIES) __xps/mb_hwt2_compiler.opt
	@mkdir -p $(MB_HWT2_OUTPUT_DIR) 
	$(MB_HWT2_CC) $(MB_HWT2_CC_OPT) $(MB_HWT2_SOURCES) -o $(MB_HWT2_OUTPUT) \
	$(MB_HWT2_OTHER_CC_FLAGS) $(MB_HWT2_INCLUDES) $(MB_HWT2_LIBPATH) \
	$(MB_HWT2_CFLAGS) $(MB_HWT2_LFLAGS) 
	$(MB_HWT2_CC_SIZE) $(MB_HWT2_OUTPUT) 
	@echo ""

MB_HWT2_programclean:
	rm -f $(MB_HWT2_OUTPUT) 

#################################################################
# SOFTWARE APPLICATION MB_HWT3
#################################################################

MB_HWT3_program: $(MB_HWT3_OUTPUT) 

$(MB_HWT3_OUTPUT) : $(MB_HWT3_SOURCES) $(MB_HWT3_HEADERS) $(MB_HWT3_LINKER_SCRIPT) \
                    $(LIBRARIES) __xps/mb_hwt3_compiler.opt
	@mkdir -p $(MB_HWT3_OUTPUT_DIR) 
	$(MB_HWT3_CC) $(MB_HWT3_CC_OPT) $(MB_HWT3_SOURCES) -o $(MB_HWT3_OUTPUT) \
	$(MB_HWT3_OTHER_CC_FLAGS) $(MB_HWT3_INCLUDES) $(MB_HWT3_LIBPATH) \
	$(MB_HWT3_CFLAGS) $(MB_HWT3_LFLAGS) 
	$(MB_HWT3_CC_SIZE) $(MB_HWT3_OUTPUT) 
	@echo ""

MB_HWT3_programclean:
	rm -f $(MB_HWT3_OUTPUT) 

#################################################################
# SOFTWARE APPLICATION MB_HWT4
#################################################################

MB_HWT4_program: $(MB_HWT4_OUTPUT) 

$(MB_HWT4_OUTPUT) : $(MB_HWT4_SOURCES) $(MB_HWT4_HEADERS) $(MB_HWT4_LINKER_SCRIPT) \
                    $(LIBRARIES) __xps/mb_hwt4_compiler.opt
	@mkdir -p $(MB_HWT4_OUTPUT_DIR) 
	$(MB_HWT4_CC) $(MB_HWT4_CC_OPT) $(MB_HWT4_SOURCES) -o $(MB_HWT4_OUTPUT) \
	$(MB_HWT4_OTHER_CC_FLAGS) $(MB_HWT4_INCLUDES) $(MB_HWT4_LIBPATH) \
	$(MB_HWT4_CFLAGS) $(MB_HWT4_LFLAGS) 
	$(MB_HWT4_CC_SIZE) $(MB_HWT4_OUTPUT) 
	@echo ""

MB_HWT4_programclean:
	rm -f $(MB_HWT4_OUTPUT) 

#################################################################
# SOFTWARE APPLICATION MB_HWT5
#################################################################

MB_HWT5_program: $(MB_HWT5_OUTPUT) 

$(MB_HWT5_OUTPUT) : $(MB_HWT5_SOURCES) $(MB_HWT5_HEADERS) $(MB_HWT5_LINKER_SCRIPT) \
                    $(LIBRARIES) __xps/mb_hwt5_compiler.opt
	@mkdir -p $(MB_HWT5_OUTPUT_DIR) 
	$(MB_HWT5_CC) $(MB_HWT5_CC_OPT) $(MB_HWT5_SOURCES) -o $(MB_HWT5_OUTPUT) \
	$(MB_HWT5_OTHER_CC_FLAGS) $(MB_HWT5_INCLUDES) $(MB_HWT5_LIBPATH) \
	$(MB_HWT5_CFLAGS) $(MB_HWT5_LFLAGS) 
	$(MB_HWT5_CC_SIZE) $(MB_HWT5_OUTPUT) 
	@echo ""

MB_HWT5_programclean:
	rm -f $(MB_HWT5_OUTPUT) 

#################################################################
# BOOTLOOP ELF FILES
#################################################################



$(PPC440_0_BOOTLOOP): $(PPC440_BOOTLOOP)
	@mkdir -p $(BOOTLOOP_DIR)
	cp -f $(PPC440_BOOTLOOP) $(PPC440_0_BOOTLOOP)

$(MICROBLAZE_0_BOOTLOOP): $(MICROBLAZE_BOOTLOOP)
	@mkdir -p $(BOOTLOOP_DIR)
	cp -f $(MICROBLAZE_BOOTLOOP) $(MICROBLAZE_0_BOOTLOOP)

$(MICROBLAZE_1_BOOTLOOP): $(MICROBLAZE_BOOTLOOP)
	@mkdir -p $(BOOTLOOP_DIR)
	cp -f $(MICROBLAZE_BOOTLOOP) $(MICROBLAZE_1_BOOTLOOP)

$(MICROBLAZE_2_BOOTLOOP): $(MICROBLAZE_BOOTLOOP)
	@mkdir -p $(BOOTLOOP_DIR)
	cp -f $(MICROBLAZE_BOOTLOOP) $(MICROBLAZE_2_BOOTLOOP)

$(MICROBLAZE_MB3_BOOTLOOP): $(MICROBLAZE_BOOTLOOP)
	@mkdir -p $(BOOTLOOP_DIR)
	cp -f $(MICROBLAZE_BOOTLOOP) $(MICROBLAZE_MB3_BOOTLOOP)

$(MICROBLAZE_MB4_BOOTLOOP): $(MICROBLAZE_BOOTLOOP)
	@mkdir -p $(BOOTLOOP_DIR)
	cp -f $(MICROBLAZE_BOOTLOOP) $(MICROBLAZE_MB4_BOOTLOOP)

$(MICROBLAZE_MB5_BOOTLOOP): $(MICROBLAZE_BOOTLOOP)
	@mkdir -p $(BOOTLOOP_DIR)
	cp -f $(MICROBLAZE_BOOTLOOP) $(MICROBLAZE_MB5_BOOTLOOP)

#################################################################
# HARDWARE IMPLEMENTATION FLOW
#################################################################


$(BMM_FILE) \
$(WRAPPER_NGC_FILES): $(MHSFILE) __xps/platgen.opt \
                      $(CORE_STATE_DEVELOPMENT_FILES)
	@echo "****************************************************"
	@echo "Creating system netlist for hardware specification.."
	@echo "****************************************************"
	platgen $(PLATGEN_OPTIONS) $(MHSFILE)

$(POSTSYN_NETLIST): $(WRAPPER_NGC_FILES)
	@echo "Running synthesis..."
	bash -c "cd synthesis; ./synthesis.sh"

__xps/$(SYSTEM)_routed: $(FPGA_IMP_DEPENDENCY)
	@echo "*********************************************"
	@echo "Running Xilinx Implementation tools.."
	@echo "*********************************************"
	@cp -f $(UCF_FILE) implementation/$(SYSTEM).ucf
	xilperl $(NON_CYG_XILINX_EDK_DIR)/data/fpga_impl/manage_fastruntime_opt.pl $(MANAGE_FASTRT_OPTIONS)
	xflow -wd implementation -p $(DEVICE) -implement xflow.opt $(SYSTEM).ngc
	touch __xps/$(SYSTEM)_routed

$(SYSTEM_BIT): __xps/$(SYSTEM)_routed $(BITGEN_UT_FILE)
	xilperl $(NON_CYG_XILINX_EDK_DIR)/data/fpga_impl/observe_par.pl $(OBSERVE_PAR_OPTIONS) implementation/$(SYSTEM).par
	@echo "*********************************************"
	@echo "Running Bitgen.."
	@echo "*********************************************"
	@cp -f $(BITGEN_UT_FILE) implementation/bitgen.ut
	cd implementation; bitgen -w -f bitgen.ut $(SYSTEM)

$(DOWNLOAD_BIT): $(SYSTEM_BIT) $(BRAMINIT_ELF_FILES) __xps/bitinit.opt
	@cp -f implementation/$(SYSTEM)_bd.bmm .
	@echo "*********************************************"
	@echo "Initializing BRAM contents of the bitstream"
	@echo "*********************************************"
	bitinit $(MHSFILE) $(SEARCHPATHOPT) $(BRAMINIT_ELF_FILE_ARGS) \
	-bt $(SYSTEM_BIT) -o $(DOWNLOAD_BIT)
	@rm -f $(SYSTEM)_bd.bmm

$(SYSTEM_ACE):
	@echo "In order to generate ace file, you must have:-"
	@echo "- exactly one processor."
	@echo "- opb_mdm, if using microblaze."

#################################################################
# SIMULATION FLOW
#################################################################


################## BEHAVIORAL SIMULATION ##################

$(BEHAVIORAL_SIM_SCRIPT): $(MHSFILE) __xps/simgen.opt \
                          $(BRAMINIT_ELF_FILES)
	@echo "*********************************************"
	@echo "Creating behavioral simulation models..."
	@echo "*********************************************"
	simgen $(SIMGEN_OPTIONS) -m behavioral $(MHSFILE)

################## STRUCTURAL SIMULATION ##################

$(STRUCTURAL_SIM_SCRIPT): $(WRAPPER_NGC_FILES) __xps/simgen.opt \
                          $(BRAMINIT_ELF_FILES)
	@echo "*********************************************"
	@echo "Creating structural simulation models..."
	@echo "*********************************************"
	simgen $(SIMGEN_OPTIONS) -sd implementation -m structural $(MHSFILE)


################## TIMING SIMULATION ##################

$(TIMING_SIM_SCRIPT): $(SYSTEM_BIT) __xps/simgen.opt \
                      $(BRAMINIT_ELF_FILES)
	@echo "*********************************************"
	@echo "Creating timing simulation models..."
	@echo "*********************************************"
	simgen $(SIMGEN_OPTIONS) -sd implementation -m timing $(MHSFILE)

#################################################################
# VIRTUAL PLATFORM FLOW
#################################################################


$(VPEXEC): $(MHSFILE) __xps/vpgen.opt
	@echo "****************************************************"
	@echo "Creating virtual platform for hardware specification.."
	@echo "****************************************************"
	vpgen $(VPGEN_OPTIONS) $(MHSFILE)

dummy:
	@echo ""

